"""Local configuration constants for LmDbServer
"""
from LmCommon.common.config import Config
from LmCommon.common.lmconstants import SERVER_PIPELINE_HEADING, BoomKeys

# Data Archive Pipeline
WORKER_JOB_LIMIT = Config().getint(SERVER_PIPELINE_HEADING, 'WORKER_JOB_LIMIT')

INTERSECT_FILTERSTRING = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.INTERSECT_FILTER_STRING)
INTERSECT_VALNAME = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.INTERSECT_VAL_NAME)
INTERSECT_MINPERCENT = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.INTERSECT_MIN_PERCENT)
INTERSECT_MINPRESENCE = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.INTERSECT_MIN_PRESENCE)
INTERSECT_MAXPRESENCE = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.INTERSECT_MAX_PRESENCE)

# GBIF data
GBIF_TAXONOMY_FILENAME = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.GBIF_TAXONOMY_FILENAME)
GBIF_PROVIDER_FILENAME = Config().get(
    SERVER_PIPELINE_HEADING, BoomKeys.GBIF_PROVIDER_FILENAME)
GBIF_OCCURRENCE_FILENAME = Config().get(
    SERVER_PIPELINE_HEADING, 'GBIF_OCCURRENCE_FILENAME')

OCC_EXP_YEAR = Config().getint(SERVER_PIPELINE_HEADING, BoomKeys.OCC_EXP_YEAR)
OCC_EXP_MONTH = Config().getint(
    SERVER_PIPELINE_HEADING, BoomKeys.OCC_EXP_MONTH)
OCC_EXP_DAY = Config().getint(SERVER_PIPELINE_HEADING, BoomKeys.OCC_EXP_DAY)
